### ISSUE TITLE
Trying to add new inlines just shows up as text areas. Could be similar to an earlier issue

### ISSUE THREAD

**Issue by hagsteel** [aljosa/django-tinymce#90] opened 2014-04-09 21:01 UTC
Trying to add new inlines just shows up as text areas, no TinyMCE in sight.
Could be similar to an earlier issue, however it was closed years ago so perhaps this is a new one.

I've put a project on Github so all settings etc. can be seen: https://github.com/jonashagstedt/tinymceissue

Versions:
-  Django==1.6.2
-  django-tinymce==1.5.2

**Comment by radlws** [comment] 2015-01-12 16:18
using version 1.5.3, and adding inlines using the 'Add another inline' does not initialize the tinymce widget correctly, it seems to be disabled. Do we need a custom onAfterAdded to initialize it properly every time you add a new inline?

**Comment by hiltonc** [comment] 2015-04-29 20:37
I'm experiencing the same problem.

**Comment by hiltonc** [comment] 2015-04-29 21:04
http://stackoverflow.com/a/19663437 fixed it for me.

**Comment by Natim** [comment] 2015-07-23 14:40
Can you try if this is fixed with current master?

**Comment by hiltonc** [comment] 2015-07-26 20:55
I just tried with the latest Grappelli and the current master of django-tinymce, no dice.

**Comment by winfieldco** [comment] 2016-05-11 22:23
I'm using an old version 1.5.3 and stacked inlines not tabular, but this fixed it for me, just changing the javascript to find the correct row that contained the tinymce to initialize:

https://github.com/winfieldco/django-tinymce/commit/fb7e2a67f78e0316105e471663fff7b648d00267

**Closed** 2020-04-10 14:03 UTC
Labels: bug

**Comment by jgillard** [comment] 2021-03-04 11:18
We've also just run into this issue while integrating TinyMCE into Django 3.1.7. This is from a TabularInline.

<img width="845" alt="Screenshot 2021-03-04 at 11 13 15" src="https://user-images.githubusercontent.com/3770312/109955707-b5d0b200-7cda-11eb-882b-7d3c9d924a91.png">

**Comment by claudep** [comment] 2021-03-04 15:12
I would suggest creating a new ticket (you can reference this one). It would help if you could tell if any JS error occurs, or if you could debug what's happening in your case in the click handler at the bottom of the `init_tinymce.js` file. It is probably related to your specific projects, as I can confirm it works in at least in one of mine with latest Django.
