### ISSUE TITLE
JS : Imcompatibility between django-grappelli and django-tinymce

### ISSUE THREAD

**Issue by frague59** [aljosa/django-tinymce#102] opened 2014-09-23 14:03 UTC
Hi, 

I use tinymce + grappelli for several years and I've never seen that before.

My current install :
* django==1.7
* django-grappelli==2.5.0
* django-tinymce==1.5.2 (from gihub or from pypi)

The tinyMCE widget does not display, have a simple textarea instead.
In firebug, I've an error : 
	
```
ReferenceError: django is not defined
error source line:
}(django.jQuery));

http://127.0.0.1:8000/static/django_tinymce/init_tinymce.js (line 38)
```

Grappelli drops (overwrite) the :
* admin/js/jquery.min.js
* admin/js/jquery.js
* admin/js/jquery.init.js 
which provide the ``django.jQuery`` binding.

Is it possible to re-bind the ``django.jQuery`` ? or to remove this binding in tinymce ?

Thanks for your great job !

**Comment by joelburton** [comment] 2015-02-22 17:18
The problem isn't related to grappelli at all; the same problem happens with using django-tinymce directly.

You can fix this without downgrading by defining django in your template, like such:

```
  <script>
    var django = {jQuery: jQuery};
  </script>
  {{ form.media }}
```

This must be done before including the ```{{ form.media }}```

**Comment by Natim** [comment] 2015-07-23 12:23
See https://github.com/aljosa/django-tinymce/pull/108

**Comment by po5i** [comment] 2015-07-29 01:58
@joelburton solution worked for me

**Comment by Natim** [comment] 2015-07-30 07:42
I pushed a fix into master, can you try that it works fine for you guys?

**Comment by vanadium23** [comment] 2016-02-29 05:51
Closing this due to fix in master.

**Closed by vanadium23** 2016-02-29 05:51 UTC
